
import { FactionType, GamePhase, MapId } from './types';

export const UI_TEXT = {
  common: {
    back: 'Back',
    next: 'Next',
    cancel: 'Cancel',
    close: 'Close',
    select: 'Select...',
    selectFaction: 'Select a faction',
    reach: 'Reach:',
    type: 'Type:',
    step: (num: number, text: string) => `Step ${num}: ${text}`,
  },
  mainMenu: {
    tagline: 'A Digital Companion',
    newGame: 'New Game',
    continueGame: 'Continue Game',
    lawLibrary: 'Law Library',
    settingsAria: 'Settings',
  },
  lawLibrary: {
    library: 'Library',
    breadcrumbSeparator: '/',
    optionalModules: 'Optional Modules',
    factions: 'Factions',
  },
  newGameSetup: {
    player: (index: number) => `Player ${index + 1}`,
    playerName: (index: number) => `Player ${index + 1} Name`,
    playerPlaceholder: (index: number) => `Player ${index + 1}`,
    factionReach: (reach: number) => ` (R: ${reach})`,
    totalReach: 'Total Reach:',
    recommendedReach: (reach: number) => `${reach}+ Recommended`,
    factionName: (player: { name?: string }, faction: { name: string }) => `${player.name}: The ${faction.name}`,
    firstPlayer: 'The first player is ',
    stepTitles: {
      players: 'Players & Seating',
      mapModules: 'Map & Modules',
      mapSetup: (mapTitle: string) => `${mapTitle} Setup`,
      drawInitialCards: 'Draw Initial Cards',
      landmarkSetup: 'Landmark Setup',
      hirelingSetup: 'Hireling Setup',
      advancedSetupDraft: 'Advanced Setup: Faction Draft',
      factions: 'Factions',
      factionSetup: 'Faction Setup',
      finalize: 'Finalize',
    },
    numPlayers: 'Number of Players',
    setupOptions: 'Setup & Game Options',
    map: 'Map',
    useAdvancedSetup: 'Use Advanced Setup',
    useAdvancedSetupDesc: 'Draft factions and use optional modules.',
    useLandmarks: 'Use Landmarks',
    useLandmarksDesc: 'Add unique locations to the map.',
    useHirelings: 'Use Hirelings',
    useHirelingsDesc: 'Add mercenary factions to the game.',
    factionSetupInstructions: 'Follow these instructions for each player in turn order.',
    drawInitialCardsText: 'Each player draws 5 cards. You will choose your final starting hand of 3 cards after all factions have been set up.',
    finalizeText: {
      advanced: 'Each player now chooses 3 cards to keep from their hand of 5. The other 2 are shuffled back into the deck.',
      standard: 'Each player draws 3 cards.',
      ruins: "Place a ruin in each slot on the map marked with an 'R'.",
    },
    startGame: 'Start Game!',
  },
  turnDashboard: {
    noActiveGame: 'No active game.',
    goToMainMenu: 'Go to Main Menu',
    playersTurn: "Player's Turn:",
    actionsForPhase: (phase: string) => `Actions for ${phase}`,
    noActionsForPhase: 'No specific actions for this phase.',
    libraryAria: 'Library',
    playersAria: 'Players',
    exitGameAria: 'Exit Game',
    endTurn: 'End Turn',
    nextPhase: 'Next Phase',
    players: 'Players',
    rules: 'Rules',
    factionDetailsTitle: (name: string) => `${name}'s Faction`,
    factionSeparator: (name: string) => `- ${name}`,
  },
  factionDetail: {
    howToWin: 'How to Win',
    specialAbilities: 'Special Abilities',
    showSetup: 'Show Faction Setup',
    mechanics: 'Mechanics',
    howToPlay: 'How to Play',
    strategy: 'Strategy',
    turnBreakdown: 'Turn Breakdown',
  },
  settings: {
    title: 'Settings',
    preventScreenLock: 'Prevent Screen Lock',
    preventScreenLockDesc: 'Keeps the screen on during gameplay.',
    language: 'Language',
    languageDesc: 'Select the application language.',
    backToMainMenu: 'Back to Main Menu',
    languages: {
      en: 'English',
      pl: 'Polish',
    },
  },
  gamePhase: {
    [GamePhase.BIRDSONG]: 'Birdsong',
    [GamePhase.DAYLIGHT]: 'Daylight',
    [GamePhase.EVENING]: 'Evening',
  },
  factionType: {
    [FactionType.MILITANT]: 'Militant',
    [FactionType.INSURGENT]: 'Insurgent',
  },
  mapId: {
    [MapId.FALL]: 'Fall Map (Default)',
    [MapId.WINTER]: 'Winter Map',
    [MapId.LAKE]: 'Lake Map',
    [MapId.MOUNTAIN]: 'Mountain Map',
  },
  mapTitle: {
    [MapId.FALL]: 'Fall Map',
    [MapId.WINTER]: 'Winter Map',
    [MapId.LAKE]: 'Lake Map',
    [MapId.MOUNTAIN]: 'Mountain Map',
  },
};