
import { FactionType, GamePhase, MapId } from './types';

export const UI_TEXT_PL = {
  common: {
    back: 'Wstecz',
    next: 'Dalej',
    cancel: 'Anuluj',
    close: 'Zamknij',
    select: 'Wybierz...',
    selectFaction: 'Wybierz frakcję',
    reach: 'Zasięg:',
    type: 'Typ:',
    step: (num: number, text: string) => `Krok ${num}: ${text}`,
  },
  mainMenu: {
    tagline: 'Cyfrowy Kompan',
    newGame: 'Nowa gra',
    continueGame: 'Kontynuuj grę',
    lawLibrary: 'Księga praw',
    settingsAria: 'Ustawienia',
  },
  lawLibrary: {
    library: 'Księga',
    breadcrumbSeparator: '/',
    optionalModules: 'Moduły opcjonalne',
    factions: 'Frakcje',
  },
  newGameSetup: {
    player: (index: number) => `Gracz ${index + 1}`,
    playerName: (index: number) => `Nazwa gracza ${index + 1}`,
    playerPlaceholder: (index: number) => `Gracz ${index + 1}`,
    factionReach: (reach: number) => ` (Z: ${reach})`,
    totalReach: 'Całkowity zasięg:',
    recommendedReach: (reach: number) => `${reach}+ zalecany`,
    factionName: (player: { name?: string }, faction: { name: string }) => `${player.name}: ${faction.name}`,
    firstPlayer: 'Pierwszym graczem jest ',
    stepTitles: {
      players: 'Gracze i miejsca',
      mapModules: 'Mapa i moduły',
      mapSetup: (mapTitle: string) => `Przygotowanie ${mapTitle}`,
      drawInitialCards: 'Dobierz karty początkowe',
      landmarkSetup: 'Przygotowanie punktów terenu',
      hirelingSetup: 'Przygotowanie zaciężnych',
      advancedSetupDraft: 'Przygotowanie zaawansowane: Draft frakcji',
      factions: 'Frakcje',
      factionSetup: 'Przygotowanie frakcji',
      finalize: 'Finalizacja',
    },
    numPlayers: 'Liczba graczy',
    setupOptions: 'Opcje gry i przygotowania',
    map: 'Mapa',
    useAdvancedSetup: 'Użyj przygotowania zaawansowanego',
    useAdvancedSetupDesc: 'Wybierz frakcje w drafcie i użyj modułów opcjonalnych.',
    useLandmarks: 'Użyj punktów terenu',
    useLandmarksDesc: 'Dodaj unikalne punkty terenu do mapy.',
    useHirelings: 'Użyj zaciężnych',
    useHirelingsDesc: 'Dodaj do gry frakcje zaciężnych.',
    factionSetupInstructions: 'Postępuj zgodnie z tymi instrukcjami dla każdego gracza w kolejności tur.',
    drawInitialCardsText: 'Każdy gracz dobiera 5 kart. Ostateczną rękę startową złożoną z 3 kart wybierzesz po przygotowaniu wszystkich frakcji.',
    finalizeText: {
      advanced: 'Każdy gracz wybiera teraz 3 karty do zatrzymania z ręki 5 kart. Pozostałe 2 są wtasowywane z powrotem do talii.',
      standard: 'Każdy gracz dobiera 3 karty.',
      ruins: "Umieść ruinę na każdym polu na mapie oznaczonym literą 'R'.",
    },
    startGame: 'Rozpocznij grę!',
  },
  turnDashboard: {
    noActiveGame: 'Brak aktywnej gry.',
    goToMainMenu: 'Przejdź do menu głównego',
    playersTurn: "Tura gracza:",
    actionsForPhase: (phase: string) => `Akcje w fazie: ${phase}`,
    noActionsForPhase: 'Brak określonych akcji dla tej fazy.',
    libraryAria: 'Księga Praw',
    playersAria: 'Gracze',
    exitGameAria: 'Zakończ Grę',
    endTurn: 'Zakończ turę',
    nextPhase: 'Następna faza',
    players: 'Gracze',
    rules: 'Zasady',
    factionDetailsTitle: (name: string) => `Szczegóły Frakcji: ${name}`,
    factionSeparator: (name: string) => `- ${name}`,
  },
  factionDetail: {
    howToWin: 'Jak wygrać',
    specialAbilities: 'Zdolności specjalne',
    showSetup: 'Pokaż przygotowanie frakcji',
    mechanics: 'Mechanika',
    howToPlay: 'Jak grać',
    strategy: 'Strategia',
    turnBreakdown: 'Przebieg tury',
  },
  settings: {
    title: 'Ustawienia',
    preventScreenLock: 'Zapobiegaj wygaszaniu ekranu',
    preventScreenLockDesc: 'Utrzymuje ekran włączony podczas rozgrywki.',
    language: 'Język',
    languageDesc: 'Wybierz język aplikacji.',
    backToMainMenu: 'Powrót do menu głównego',
    languages: {
      en: 'Angielski',
      pl: 'Polski',
    },
  },
  gamePhase: {
    [GamePhase.BIRDSONG]: 'Świt',
    [GamePhase.DAYLIGHT]: 'Dzień',
    [GamePhase.EVENING]: 'Wieczór',
  },
  factionType: {
    [FactionType.MILITANT]: 'Militarna',
    [FactionType.INSURGENT]: 'Powstańcza',
  },
  mapId: {
    [MapId.FALL]: 'Mapa Jesienna (Domyślna)',
    [MapId.WINTER]: 'Mapa Zimowa',
    [MapId.LAKE]: 'Mapa Jeziora',
    [MapId.MOUNTAIN]: 'Mapa Górska',
  },
  mapTitle: {
    [MapId.FALL]: 'Mapy Jesiennej',
    [MapId.WINTER]: 'Mapy Zimowej',
    [MapId.LAKE]: 'Mapy Jeziora',
    [MapId.MOUNTAIN]: 'Mapy Górskiej',
  },
};